services:
  rss2cubox:
    container_name: rss2cubox
    image: gantedanca446/rss2cubox
    environment:
      - CUBOX_API=https://cubox.pro/c/api/save/token_to_your_cubox_api
    volumes:
      - ./timestramp.txt:/app/timestramp.txt
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host  